### ISSUE TITLE
pgfcalendar

### ISSUE THREAD

**Issue by mirabilos** [Qrrbrbirlbel/tex.sx#1]
Hi,

sorry for making an “issue” out of this, but I cannot find your pgfcalendar from http://tex.stackexchange.com/a/144186/43807 in these repositories, nor do I have another way to contact you.

I would like to kindly request to be able to reuse that code under the terms of a licence somewhat more liberal than StackExchange’s default terms (while still retaining attribution, of course), namely http://www.mirbsd.org/MirOS-Licence.htm (which even has a German translation, should that be relevant).

I implemented a whole wall calendar generator in Teχ/LaTeX under this free licence, except I rely on your pgfcalendar. If you’re interested (reviews by Teχ experts are always welcome; I still consider myself a sort of newbie), the source files for the calendar (besides the site template) are:

- https://github.com/teckids/verein/blob/master/docs/jahresplan.tex.in and https://github.com/teckids/verein/blob/master/docs/jahresplan_a3.tex.in
- https://github.com/teckids/verein/blob/master/docs/jahresplan.sh
- https://github.com/teckids/verein/blob/master/intern/jahresplan.txt (data source)
- https://github.com/teckids/verein/blob/master/templates/teckidscal.sty (main calendar production and tabular rendering)
- https://github.com/teckids/verein/blob/master/templates/pgfeaster.sty (your Easter calculation, including attribution and all)

The output looks thus: https://www.teckids.org/docs/verein/docs/jahresplan.pdf

As you can see, there’s only the Easter calculation missing, which is pretty much a straight-forwrad reference implementation, and as such contains very few copyrightable information (low threshold of originality / “Schaffenshöhe”), but I’d still wish for you to freely licence the original code instead of rewriting it (or using it as-is; large parts of our site are also CC-BY-SA 3.0 licenced, but I prefer to keep things easy whenever possible).

Thanks in advance!
//mirabilos

**Comment by Qrrbrbirlbel** [comment]
Does putting the code on [GitHub](https://github.com/Qrrbrbirlbel/tex.sx/blob/master/pgflibrarycalendar.easter.code.tex) help you?

Sorry for the late response, TeX and friends aren't currently on my radar.

**Comment by mirabilos** [comment]
Thank you, adding it here and with a permissive licence helps! Will merge that.

**Comment by mirabilos** [comment]
Qrrbrbirlbel dixit:

>I hope
>[pgflibrarycalendar.easter.code.tex](https://github.com/Qrrbrbirlbel/tex.sx/blob/master/pgflibrarycalendar.easter.code.tex)
>makes you happy.

Why, yes, it did make me very happy.

Thanks!

bye,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt
